// src/components/Education.vue
<template>
  <div class="container mx-auto my-auto h-screen">
    <div class="flex flex-col mx-8">
      <article class="prose">
        <router-link to="/" class="no-underline">
          <h4 class="mt-16 text-primary">
            <font-awesome-icon icon="fa-solid fa-arrow-left" class="mr-2" />
            Lorenzo Palaia
          </h4>
        </router-link>
        <h1 class="mb-16">Education</h1>
      </article>
      <table class="table">
        <thead class="sticky top-0 backdrop-blur">
          <tr class="border-b-neutral-800">
            <th class="text-neutral-200 font-bold table-cell">Period</th>
            <th class="text-neutral-200 font-bold table-cell">Degree</th>
            <th class="text-neutral-200 font-bold table-cell">School</th>
            <th class="text-neutral-200 font-bold hidden lg:table-cell">
              Location
            </th>
            <th class="text-neutral-200 font-bold hidden md:table-cell">
              Link
            </th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="edu in education"
            :key="edu"
            class="border-b-neutral-800"
          >
            <td class="text-neutral-400 font-light table-cell">
              {{ edu.date }}
            </td>
            <td class="text-neutral-200 font-bold table-cell">
              {{ edu.degree }}
            </td>
            <td class="text-neutral-400 font-light table-cell">
              {{ edu.school }}
            </td>
            <td class="text-neutral-400 font-light hidden lg:table-cell">
              {{ edu.location }}
            </td>
            <td class="text-neutral-400 font-light hidden md:table-cell group">
              <a
                :href="edu.url"
                target="_blank"
                class="group-hover:text-primary transition duration-250 ease-in-out"
              >
                {{ edu.url.replace(/^(https?:\/\/)?(www\.)?/i, '') }}
                <font-awesome-icon
                  v-if="edu.url"
                  icon="fa-solid fa-arrow-right"
                  class="ml-2"
                />
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import personalInfo from "../assets/personalInfo.json";

export default {
  data: () => ({
    education: personalInfo.education,
  }),

  mounted() {
    document.title = "Education | Lorenzo Palaia";
    window.scrollTo(0, 0);
  },
};
</script>

<style></style>

// components/Education.tsx
"use client";

import config from "@/config";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight } from "@fortawesome/free-solid-svg-icons";

const Education = () => {
    return (
        <section id="education" className="section">
            <div className="group">
                {config.education.map((degree) => (
                    <div
                        key={degree.id || degree.degree} // Use unique identifier (if provided) or fallback
                        className={`flex group-hover:opacity-50 hover:bg-white/5 hover:!opacity-100 mb-8 rounded-md group/inside hover:border-t border-white/10 transition ease-in-out duration-250 ${
                            degree.url ? "cursor-pointer" : ""
                        }`}
                        onClick={() =>
                            degree.url && window.open(degree.url, "_blank")
                        }
                    >
                        {degree.show && (
                            <>
                                <div className="w-1/4 mx-4">
                                    <p className="uppercase font-light text-neutral-400 text-sm mt-6">
                                        {degree.date}
                                    </p>
                                </div>
                                <div className="w-3/4 mx-4">
                                    <p
                                        className={`group-hover/inside:text-primary text-neutral-300 font-normal mb-0`}
                                    >
                                        {degree.degree}
                                        {degree.url && (
                                            <FontAwesomeIcon
                                                icon={faArrowRight}
                                                className="ml-2 group-hover/inside:ml-3"
                                            />
                                        )}
                                    </p>
                                    <p className="font-light text-neutral-400 mt-0">
                                        {degree.school}
                                    </p>
                                    {degree.description.map(
                                        (description, index) => (
                                            <p
                                                key={index}
                                                className="font-extralight"
                                            >
                                                {description}
                                            </p>
                                        )
                                    )}
                                </div>
                            </>
                        )}
                    </div>
                ))}
            </div>
            <Link href="/education" className="no-underline">
                <p className="mb-32 mx-4 group hover:underline decoration-primary">
                    View All Education
                    <FontAwesomeIcon
                        icon={faArrowRight}
                        className="ml-2 group-hover:ml-3"
                    />
                </p>
            </Link>
        </section>
    );
};

export default Education;
