// src/components/ExtraActivities.vue
<template>
  <div class="container mx-auto my-auto">
    <div class="flex flex-col mx-8">
      <article class="prose">
        <router-link to="/" class="no-underline">
          <h4 class="mt-16 text-primary">
            <font-awesome-icon icon="fa-solid fa-arrow-left" class="mr-2" />
            Lorenzo Palaia
          </h4>
        </router-link>
        <h1 class="mb-16">Extra Activities</h1>
      </article>
      <table class="table">
        <thead class="sticky top-0 backdrop-blur">
          <tr class="border-b-neutral-800">
            <th class="text-neutral-200 font-bold table-cell">Period</th>
            <th class="text-neutral-200 font-bold table-cell">Activty</th>
            <th class="text-neutral-200 font-bold table-cell">Role</th>
            <th class="text-neutral-200 font-bold hidden lg:table-cell">
              Location
            </th>
            <th class="text-neutral-200 font-bold hidden lg:table-cell">
              Technologies
            </th>
            <th class="text-neutral-200 font-bold hidden md:table-cell">
              Link
            </th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="activity in extraActivities"
            :key="activity"
            class="border-b-neutral-800"
          >
            <td class="text-neutral-400 font-light table-cell">
              {{ activity.date }}
            </td>
            <td class="text-neutral-200 font-bold table-cell">
              {{ activity.name }}
            </td>
            <td class="text-neutral-400 font-light table-cell">
              {{ activity.role }}
            </td>
            <td class="text-neutral-400 font-light hidden lg:table-cell">
              {{ activity.location }}
            </td>
            <td class="hidden lg:table-cell">
              <div
                v-for="badge in activity.badges"
                :key="badge"
                class="badge badge-lg badge-secondary m-1"
              >
                <p class="text-primary font-light">{{ badge }}</p>
              </div>
            </td>
            <td class="text-neutral-400 font-light hidden md:table-cell group">
              <a
                :href="activity.url"
                target="_blank"
                class="group-hover:text-primary transition duration-250 ease-in-out"
              >
                {{ activity.url.replace(/^(https?:\/\/)?(www\.)?/i, "") }}
                <font-awesome-icon
                  v-if="activity.url"
                  icon="fa-solid fa-arrow-right"
                  class="ml-2"
                />
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import personalInfo from "../assets/personalInfo.json";

export default {
  data: () => ({
    extraActivities: personalInfo.extraActivities,
  }),

  mounted() {
    document.title = "Work activity | Lorenzo Palaia";
    window.scrollTo(0, 0);
  },
};
</script>

<style></style>

// components/ExtraActivities.tsx
"use client";

import config from "@/config";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight } from "@fortawesome/free-solid-svg-icons";

const ExtraActivities = () => {
    return (
        <section id="extra-activities" className="section">
            <div className="group">
                {config.extraActivities.map((activity) => (
                    <div
                        key={activity.id || activity.name} // Use unique identifier (if provided) or fallback
                        className={`flex group-hover:opacity-50 hover:bg-white/5 hover:!opacity-100 mb-8 rounded-md group/inside hover:border-t border-white/10 transition ease-in-out duration-250 ${
                            activity.url ? "cursor-pointer" : ""
                        }`}
                        onClick={() =>
                            activity.url && window.open(activity.url, "_blank")
                        }
                    >
                        {activity.show && (
                            <>
                                <div className="w-1/4 mx-4">
                                    <p className="uppercase font-light text-neutral-400 text-sm mt-6">
                                        {activity.date}
                                    </p>
                                </div>
                                <div className="w-3/4 mx-4">
                                    <p
                                        className={`group-hover/inside:text-primary text-neutral-300 font-normal mb-0`}
                                    >
                                        {activity.name}
                                        {activity.url && (
                                            <FontAwesomeIcon
                                                icon={faArrowRight}
                                                className="ml-2 group-hover/inside:ml-3"
                                            />
                                        )}
                                    </p>
                                    <p className="font-light text-neutral-400 mt-0">
                                        {activity.role}
                                    </p>
                                    {activity.description.map(
                                        (description, index) => (
                                            <p
                                                key={index}
                                                className="font-extralight"
                                            >
                                                {description}
                                            </p>
                                        )
                                    )}
                                    <div className="flex flex-wrap">
                                        {activity.badges.map((badge, index) => (
                                            <div
                                                key={index}
                                                className="badge badge-lg badge-secondary mr-2 mb-8"
                                            >
                                                <p className="text-primary font-light">
                                                    {badge}
                                                </p>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </>
                        )}
                    </div>
                ))}
            </div>
            <Link href="/extra-activities" className="no-underline">
                <p className="mb-32 mx-4 group hover:underline decoration-primary">
                    View All Extra Activities
                    <FontAwesomeIcon
                        icon={faArrowRight}
                        className="ml-2 group-hover:ml-3"
                    />
                </p>
            </Link>
        </section>
    );
};

export default ExtraActivities;
