// components/Projects.tsx
"use client";

import config from "@/config";
import Link from "next/link";
import Image from "next/image";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight, faStar } from "@fortawesome/free-solid-svg-icons";

const Projects = () => {
    return (
        <section id="projects" className="section">
            {config.projects.length === 0 && (
                <div>
                    {/* Render loading skeletons if no projects */}
                    {Array.from({ length: 3 }).map((_, index) => (
                        <div
                            key={index}
                            className="skeleton w-full h-48 mb-8 opacity-50"
                        />
                    ))}
                </div>
            )}
            {config.projects.length > 0 && (
                <div className="group">
                    {config.projects.map((project) => (
                        <div
                            key={project.id || project.name} // Use unique identifier (if provided) or fallback
                            className={`flex flex-col lg:flex-row group-hover:opacity-50 hover:bg-white/5 hover:!opacity-100 mb-8 rounded-md group/inside hover:border-t border-white/10 transition ease-in-out duration-250 ${
                                project.url ? "cursor-pointer" : ""
                            }`}
                            onClick={() =>
                                project.html_url &&
                                window.open(project.html_url, "_blank")
                            }
                        >
                            <div className="mx-4 order-2 lg:order-1 lg:w-1/4">
                                <Image
                                    src={project.repo_preview}
                                    alt="Project Preview"
                                    className="lg:mt-6 mt-0 rounded"
                                    style={{
                                        border: "3px solid rgba(255, 255, 255, 0.075)",
                                    }}
                                    width={300}
                                    height={300}
                                />
                            </div>
                            <div className="w-3/4 mx-4 order-1">
                                <p
                                    className={`group-hover/inside:text-primary lg:order-2 text-neutral-300 font-normal mb-0`}
                                >
                                    {project.name.replace(/-/g, " ")}
                                    {project.url && (
                                        <FontAwesomeIcon
                                            icon={faArrowRight}
                                            className="ml-2 group-hover/inside:ml-3"
                                        />
                                    )}
                                </p>
                                <p className="font-extralight">
                                    {project.description}
                                </p>
                                {project.hasOwnProperty("stargazers_count") && (
                                    <p className="text-neutral-500">
                                        <FontAwesomeIcon
                                            icon={faStar}
                                            className="mr-1"
                                        />
                                        {project.stargazers_count}
                                    </p>
                                )}
                                <div className="flex flex-wrap">
                                    {project.languages.map((language) => (
                                        <div
                                            key={language}
                                            className="badge badge-lg badge-secondary mr-2 mb-8"
                                        >
                                            <p className="text-primary font-light">
                                                {language}
                                            </p>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}
            <Link href="/projects" className="no-underline">
                <p className="mb-32 mx-4 group hover:underline decoration-primary">
                    View All Projects
                    <FontAwesomeIcon
                        icon={faArrowRight}
                        className="ml-2 group-hover:ml-3"
                    />
                </p>
            </Link>
        </section>
    );
};

export default Projects;

// src/components/Projects.vue
<template>
  <div class="container mx-auto my-auto h-screen">
    <div class="flex flex-col mx-8">
      <article class="prose">
        <router-link to="/" class="no-underline">
          <h4 class="mt-16 text-primary">
            <font-awesome-icon icon="fa-solid fa-arrow-left" class="mr-2" />
            Lorenzo Palaia
          </h4>
        </router-link>
        <h1 class="mb-16">Projects</h1>
      </article>
      <div v-if="projects && projects.length === 0">
        <div class="skeleton w-full h-48 mb-8 opacity-50"></div>
      </div>
      <table v-else class="table">
        <thead class="sticky top-0 backdrop-blur">
          <tr class="border-b-neutral-800">
            <th class="text-neutral-200 font-bold table-cell">Updated</th>
            <th class="text-neutral-200 font-bold hidden lg:table-cell">
              Started
            </th>
            <th class="text-neutral-200 font-bold table-cell">Project</th>
            <th class="text-neutral-200 font-bold hidden md:table-cell">
              Technologies
            </th>
            <th class="text-neutral-200 font-bold hidden xl:table-cell">
              Link
            </th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="project in projects"
            :key="project"
            class="border-b-neutral-800"
          >
            <td class="text-neutral-400 font-light table-cell">
              {{
                new Date(project.pushed_at).toLocaleDateString("en-US", {
                  year: "numeric",
                  month: "short",
                })
              }}
            </td>
            <td class="text-neutral-400 font-light hidden lg:table-cell">
              {{
                new Date(project.created_at).toLocaleDateString("en-US", {
                  year: "numeric",
                  month: "short",
                })
              }}
            </td>
            <td class="text-neutral-200 font-bold table-cell">
              {{ project.name.replace(/-/g, " ") }}
            </td>
            <td class="hidden xl:table-cell">
              <div
                v-for="language in project.languages"
                :key="language"
                class="badge badge-lg badge-secondary m-1"
              >
                <p class="text-primary">{{ language }}</p>
              </div>
            </td>
            <td class="text-neutral-400 font-light hidden md:table-cell group">
              <a
                :href="project.html_url"
                target="_blank"
                class="group-hover:text-primary transition duration-250 ease-in-out"
              >
                {{ project.html_url.replace(/^(https?:\/\/)?(www\.)?/i, "") }}
                <font-awesome-icon
                  icon="fa-solid fa-arrow-right"
                  class="ml-2"
                />
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import {
  fetchRepos,
  redirectToExternalLink,
} from "../utils/api.js";

export default {
  data: () => ({
    projects: [],
  }),

  methods: {
    async getReposAndSort(username) {
      const data = await fetchRepos(username)
      this.projects = data.sort((a, b) => new Date(b.pushed_at) - new Date(a.pushed_at));
    },
    redirectToExternalLink,
  },

  mounted() {
    document.title = "Projects | Lorenzo Palaia";
    window.scrollTo(0, 0, "smooth");
    this.getReposAndSort("lorenzopalaia");
  },
};
</script>

<style></style>
